name: 'Chromatic, Jest, and Cypress'

on: push

jobs:
  jest:
    name: Run Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test -- --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: tottenj/flare_webapp

  cypress:
    name: Run Cypress E2E
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:26.1.4
        options: >-
          --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start docker-compose
        run: docker compose -f docker-compose.yml up --build -d

      - name: Wait for app
        run: npx wait-on http://localhost:3000

      - name: Run Cypress
        run: docker compose run --rm cypress

      - name: Stop docker-compose
        if: always()
        run: docker compose down -v
